# Generated by Django 4.2.2 on 2023-07-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='AboutUs')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='AboutUs')),
                ('phoneNo', models.CharField(max_length=9)),
                ('mobileNo', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='Banner')),
                ('weight', models.IntegerField()),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
