# Generated by Django 4.2.1 on 2023-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Waitingapproval', 'Waiting approval'), ('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=50),
        ),
    ]
