# Generated by Django 4.2.1 on 2023-06-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ceeated_at',
            new_name='created_at',
        ),
    ]
